version: '3.8'
services:
  coffeemachine:
    image: "${COFFEEMACHINE_IMAGE}:${COFFEEMACHINE_TAG}"
    ports: 
      - "${COFFEEMACHINE_HTTP_PORT}:3000"
    #For future use of in memory DB like H2
    #volumes:
    #  - ./db:/tmp/db
    env_file:
     - ./.env
    environment:
      - GIN_MODE=${GIN_MODE}