apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "CoffeeMachine.fullname" . }}
  labels:
    app.kubernetes.io/component: CoffeeMachine
    {{- include "CoffeeMachine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "CoffeeMachine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        io.kubernetes.container.name: CoffeeMachine-{{ include "CoffeeMachine.fullname" . }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "CoffeeMachine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env: 
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}