apiVersion: v1
kind: Service
metadata:
  name: {{ include "CoffeeMachine.fullname" . }}
  labels:
    {{- include "CoffeeMachine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_api_port }}
      targetPort: {{ .Values.service.http_api_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "CoffeeMachine.selectorLabels" . | nindent 4 }}
