name: CI-CoffeeMachineRestApiV2
on: push

jobs: 
  runs_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.21
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test internal/models

