name: CI-CoffeeMachineRestApiV3
on: push

jobs: 
  Build_golang_app :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: 1.21
      - name: Set variables
        run: |
          VER=$(cat deployments/CoffeeMachineRestApiV3/sem.ver)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Run linting
        run: |
          go fmt ./...
          go vet -copylocks=false ./...
      - name: Run tests
        run: go test ./internal/models
      - name: Create build directory
        run : |
          mkdir deployments/CoffeeMachineRestApiV3/CoffeeMachine
          mkdir deployments/CoffeeMachineRestApiV3/CoffeeMachine/cmd
          cp -R internal deployments/CoffeeMachineRestApiV3/CoffeeMachine/internal
          cp -R cmd/CoffeeMachineRestApiV3 deployments/CoffeeMachineRestApiV3/CoffeeMachine/cmd/CoffeeMachineRestApiV3
          cp go.mod deployments/CoffeeMachineRestApiV3/CoffeeMachine
          cp go.sum deployments/CoffeeMachineRestApiV3/CoffeeMachine
      - name: Build Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: deployments/CoffeeMachineRestApiV3/CoffeeMachine
          # Path to the Dockerfile
          build-args: --progress=plain
          file: ./deployments/CoffeeMachineRestApiV3/Dockerfile
          # List of tags
          tags: github.com/kostovic/coffeemachine/restapiv3:${{ env.VERSION }}.${{github.run_number}}

