name: CI-CoffeeMachineRestApiV2
on: push

jobs: 
  runs_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: 1.21
      - name: Set variables
        run: |
          VER=$(cat deployments/CoffeeMachineRestApiV2/sem.ver)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Run linting
        run: |
          go fmt ./...
          go vet -copylocks=false ./...
      - name: Run tests
        run: go test ./internal/models
      - name: Create build directory
        run : |
          mkdir CoffeeMachine
          cp -R internal CoffeeMachine/internal
          cp -R cmd/CoffeeMachineRestApiV2 CoffeeMachine\cmd\CoffeeMachineRestApiV2
          cp go.mod CoffeeMachine
          cp go.sum CoffeeMachine
      - name: Build Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./CoffeeMachine
          # Path to the Dockerfile
          file: ./deployments/CoffeeMachineRestApiV2/Dockerfile
          # List of tags
          tags: ${{ env.VERSION }}.${{github.run_number}}

